## Project 5 ##

Data Preprocessing

In [141]:
#imports

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [142]:
pd.set_option('display.max_columns', 100)

In [143]:
pd.set_option('display.max_rows', 100)

In [144]:
intakes = pd.read_csv('../datasets/Austin_Animal_Center_Intakes.csv')

intakes.head()

,Animal ID,Name,DateTime,MonthYear,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
0,A786884,*Brock,01/03/2019 04:19:00 PM,01/03/2019 04:19:00 PM,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,2 years,Beagle Mix,Tricolor
1,A706918,Belle,07/05/2015 12:59:00 PM,07/05/2015 12:59:00 PM,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver
2,A724273,Runster,04/14/2016 06:43:00 PM,04/14/2016 06:43:00 PM,2818 Palomino Trail in Austin (TX),Stray,Normal,Dog,Intact Male,11 months,Basenji Mix,Sable/White
3,A665644,NaN,10/21/2013 07:59:00 AM,10/21/2013 07:59:00 AM,Austin (TX),Stray,Sick,Cat,Intact Female,4 weeks,Domestic Shorthair Mix,Calico
4,A682524,Rio,06/29/2014 10:38:00 AM,06/29/2014 10:38:00 AM,800 Grove Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray

In [145]:
intakes.shape

(129677, 12)

In [146]:
outcomes = pd.read_csv('../datasets/Austin_Animal_Center_Outcomes.csv')

outcomes.columns = outcomes.columns.str.lower().str.replace(' ', '_')

outcomes.head()

,animal_id,name,datetime,monthyear,date_of_birth,outcome_type,outcome_subtype,animal_type,sex_upon_outcome,age_upon_outcome,breed,color
0,A794011,Chunk,05/08/2019 06:20:00 PM,05/08/2019 06:20:00 PM,05/02/2017,Rto-Adopt,NaN,Cat,Neutered Male,2 years,Domestic Shorthair Mix,Brown Tabby/White
1,A776359,Gizmo,07/18/2018 04:02:00 PM,07/18/2018 04:02:00 PM,07/12/2017,Adoption,NaN,Dog,Neutered Male,1 year,Chihuahua Shorthair Mix,White/Brown
2,A821648,NaN,08/16/2020 11:38:00 AM,08/16/2020 11:38:00 AM,08/16/2019,Euthanasia,NaN,Other,Unknown,1 year,Raccoon,Gray
3,A720371,Moose,02/13/2016 05:59:00 PM,02/13/2016 05:59:00 PM,10/08/2015,Adoption,NaN,Dog,Neutered Male,4 months,Anatol Shepherd/Labrador Retriever,Buff
4,A674754,NaN,03/18/2014 11:47:00 AM,03/18/2014 11:47:00 AM,03/12/2014,Transfer,Partner,Cat,Intact Male,6 days,Domestic Shorthair Mix,Orange Tabby

In [147]:
outcomes.shape

(129666, 12)

In [148]:
outcomes['age_upon_outcome'].unique()

array(['2 years', '1 year', '4 months', '6 days', '7 years', '2 months',
       '2 days', '3 weeks', '9 months', '4 weeks', '2 weeks', '3 months',
       '9 years', '10 years', '6 months', '8 years', '3 years',
       '7 months', '6 years', '4 years', '1 month', '12 years', '5 years',
       '1 weeks', '5 months', '5 days', '15 years', '11 months',
       '10 months', '4 days', '16 years', '1 day', '8 months', '11 years',
       '13 years', '1 week', '14 years', '3 days', '0 years', '5 weeks',
       '17 years', '18 years', '20 years', '22 years', '-2 years',
       '19 years', '23 years', '24 years', '-1 years', '25 years',
       '21 years', '-3 years', nan], dtype=object)

In [149]:
outcomes = outcomes[~(outcomes['age_upon_outcome'] == '0 years' )]

In [150]:
outcomes = outcomes[~(outcomes['age_upon_outcome'] == '-2 years' )]

In [151]:
outcomes = outcomes[~(outcomes['age_upon_outcome'] == '-1 years' )]

In [152]:
outcomes = outcomes[~(outcomes['age_upon_outcome'] == '-3 years' )]

In [153]:
outcomes = outcomes[~(outcomes['age_upon_outcome'].isnull()==True )]

In [154]:
outcomes['age_upon_outcome'].unique()

array(['2 years', '1 year', '4 months', '6 days', '7 years', '2 months',
       '2 days', '3 weeks', '9 months', '4 weeks', '2 weeks', '3 months',
       '9 years', '10 years', '6 months', '8 years', '3 years',
       '7 months', '6 years', '4 years', '1 month', '12 years', '5 years',
       '1 weeks', '5 months', '5 days', '15 years', '11 months',
       '10 months', '4 days', '16 years', '1 day', '8 months', '11 years',
       '13 years', '1 week', '14 years', '3 days', '5 weeks', '17 years',
       '18 years', '20 years', '22 years', '19 years', '23 years',
       '24 years', '25 years', '21 years'], dtype=object)

In [155]:
def clean_age(age):
    """
        Takes a string form of age, and transforms into an a floating point number.
    """
    age_f = age.split(' ')
    if (age_f[1] == 'day' or age_f[1] == 'days'):
        return round(float(age_f[0])/365, 3)
    elif (age_f[1] == 'week' or age_f[1] == 'weeks'):
        return round(float(age_f[0])/52.143, 3)
    elif (age_f[1] == 'month' or age_f[1] == 'months'):
        return round(float(age_f[0])/12,3)
    else:
        return age[0]

In [156]:
outcomes['age_upon_outcome'] = outcomes['age_upon_outcome'].apply(clean_age).astype(float)

In [157]:
outcomes['age_upon_outcome']

0         2.000
1         1.000
2         1.000
3         0.333
4         0.016
          ...
129661    2.000
129662    1.000
129663    3.000
129664    0.083
129665    0.250
Name: age_upon_outcome, Length: 129455, dtype: float64

In [158]:
outcomes['is_named'] = outcomes['name'].notnull().astype(int)

In [159]:
outcomes.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 129455 entries, 0 to 129665
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   animal_id         129455 non-null  object
 1   name              89504 non-null   object
 2   datetime          129455 non-null  object
 3   monthyear         129455 non-null  object
 4   date_of_birth     129455 non-null  object
 5   outcome_type      129432 non-null  object
 6   outcome_subtype   59532 non-null   object
 7   animal_type       129455 non-null  object
 8   sex_upon_outcome  129454 non-null  object
 9   age_upon_outcome  129455 non-null  float64
 10  breed             129455 non-null  object
 11  color             129455 non-null  object
 12  is_named          129455 non-null  int32
dtypes: float64(1), int32(1), object(11)
memory usage: 13.3+ MB

In [160]:
outcomes.drop(columns=['monthyear'], inplace=True)

In [161]:
outcomes['outcome_subtype'].value_counts()

Partner                31889
Foster                 11505
Rabies Risk             3857
Suffering               3331
SCRP                    3210
Snr                     2769
In Kennel                633
Aggressive               555
Offsite                  431
In Foster                314
Medical                  313
At Vet                   281
Behavior                 158
Enroute                   86
Field                     49
Underage                  36
Court/Investigation       32
In Surgery                24
Possible Theft            16
Barn                      11
Prc                       10
Customer S                10
Out State                  7
Emer                       5
Name: outcome_subtype, dtype: int64

In [162]:
outcomes['outcome_type'] = outcomes[~(outcomes['outcome_type'].isnull())]

In [163]:
outcomes['animal_type'].value_counts()

Dog          73083
Cat          48848
Other         6893
Bird           610
Livestock       21
Name: animal_type, dtype: int64

In [164]:
outcomes['sex_upon_outcome'].value_counts()

Neutered Male    45584
Spayed Female    40979
Intact Male      16455
Intact Female    15987
Unknown          10449
Name: sex_upon_outcome, dtype: int64

In [165]:
outcomes['sex_upon_outcome'].replace(np.nan, 'Unknown', inplace=True)

In [166]:
outcomes['weekday'] = pd.to_datetime(outcomes['datetime']).apply(lambda x: x.day_name())

In [168]:
outcomes['month'] = pd.to_datetime(outcomes['datetime']).apply(lambda x: x.month_name())

In [169]:
outcomes['year'] = pd.to_datetime(outcomes['datetime']).apply(lambda x: x.year())

AttributeError: 'Timestamp' object has no attribute 'qyear'

In [ ]:
outcomes['datetime'] = pd.to_datetime(outcomes['datetime'])

In [ ]:
outcomes.head()

In [14]:
intakes['Intake Type'].value_counts()

Stray                 89983
Owner Surrender       25938
Public Assist          7903
Wildlife               5125
Abandoned               471
Euthanasia Request      257
Name: Intake Type, dtype: int64

In [ ]:
#find counts of unique ids in each

In [9]:
len(intakes['Animal ID'].unique())

115940

In [10]:
len(outcomes['Animal ID'].unique())

115940

In [ ]:
#find animal id value counts

In [15]:
outcomes_val_counts = outcomes['Animal ID'].value_counts()

#count of animal ids that show up more than once in dataset
len(outcomes_val_counts[outcomes_val_counts>1])

10495

In [19]:
outcomes_val_counts

A721033    33
A718223    14
A718877    12
A706536    11
A717053     9
           ..
A783627     1
A797882     1
A666791     1
A689547     1
A712333     1
Name: Animal ID, Length: 115849, dtype: int64

In [16]:
intakes_val_counts = intakes['Animal ID'].value_counts()

#count of animal ids that show up more than once in dataset
len(intakes_val_counts[intakes_val_counts>1])

10493

In [17]:
intakes_val_counts

A721033    33
A718223    14
A718877    12
A706536    11
A700407     9
           ..
A811112     1
A710624     1
A673282     1
A706958     1
A712333     1
Name: Animal ID, Length: 115865, dtype: int64

In [18]:
intakes[intakes['Animal ID']=='A721033']

,Animal ID,Name,DateTime,MonthYear,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
3726,A721033,Lil Bit,02/24/2019 09:53:00 PM,02/24/2019 09:53:00 PM,700 Allen St in Austin (TX),Public Assist,Normal,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
9714,A721033,Lil Bit,03/07/2018 08:27:00 AM,03/07/2018 08:27:00 AM,4111 South 1St in Austin (TX),Public Assist,Normal,Dog,Neutered Male,2 years,Rat Terrier Mix,Tricolor/Brown Brindle
11727,A721033,Lil Bit,05/20/2019 10:18:00 AM,05/20/2019 10:18:00 AM,1819 South Pleasant Valley Road in Austin (TX),Public Assist,Normal,Dog,Neutered Male,4 years,Rat Terrier Mix,Tricolor/Brown Brindle
12162,A721033,Lil Bit,04/05/2018 05:59:00 PM,04/05/2018 05:59:00 PM,9705 Manchaca Road in Austin (TX),Public Assist,Normal,Dog,Neutered Male,2 years,Rat Terrier Mix,Tricolor/Brown Brindle
18500,A721033,Lil Bit,09/24/2018 07:44:00 PM,09/24/2018 07:44:00 PM,Shady And Airport in Austin (TX),Public Assist,Normal,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
22147,A721033,Lil Bit,03/15/2017 09:24:00 AM,03/15/2017 09:24:00 AM,E Ben White Blvd & Montopolis Dr in Austin (TX),Public Assist,Normal,Dog,Neutered Male,1 year,Rat Terrier Mix,Tricolor/Brown Brindle
23788,A721033,Lil Bit,02/12/2019 10:21:00 AM,02/12/2019 10:21:00 AM,1936 East Oltorf Street in Austin (TX),Public Assist,Normal,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
25276,A721033,Lil Bit,09/21/2018 03:01:00 PM,09/21/2018 03:01:00 PM,863 Airport Blvd in Austin (TX),Public Assist,Normal,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
25563,A721033,Lil Bit,10/05/2019 12:31:00 PM,10/05/2019 12:31:00 PM,1135 Airport Boulevard in Austin (TX),Public Assist,Normal,Dog,Neutered Male,4 years,Rat Terrier Mix,Tricolor/Brown Brindle
26688,A721033,Lil Bit,10/20/2016 10:47:00 PM,10/20/2016 10:47:00 PM,6200 E. Ben White Blvd in Austin (TX),Public Assist,Normal,Dog,Neutered Male,1 year,Rat Terrier Mix,Tricolor/Brown Brindle
33415,A721033,Lil Bit,07/10/2016 11:53:00 AM,07/10/2016 11:53:00 AM,6317 E Ben White Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,1 year,Rat Terrier Mix,Tricolor/Brown Brindle
33645,A721033,Lil Bit,08/05/2019 10:52:00 AM,08/05/2019 10:52:00 AM,Burton And Oltorf in Austin (TX),Public Assist,Normal,Dog,Neutered Male,4 years,Rat Terrier Mix,Tricolor/Brown Brindle
35906,A721033,Lil Bit,09/03/2018 05:24:00 PM,09/03/2018 05:24:00 PM,East 7Th Street And Pleasant Valley in Austin ...,Public Assist,Normal,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
37799,A721033,Lil Bit,03/07/2019 12:02:00 PM,03/07/2019 12:02:00 PM,1500 Red River in Austin (TX),Public Assist,Normal,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
37996,A721033,Lil Bit,12/15/2016 10:07:00 AM,12/15/2016 10:07:00 AM,S Pleasant Valley Rd And E Riverside Dr in Aus...,Public Assist,Normal,Dog,Neutered Male,1 year,Rat Terrier Mix,Tricolor/Brown Brindle
38374,A721033,Lil Bit,01/30/2017 11:05:00 PM,01/30/2017 11:05:00 PM,6210 E Ben White in Austin (TX),Public Assist,Normal,Dog,Neutered Male,1 year,Rat Terrier Mix,Tricolor/Brown Brindle
48131,A721033,Lil Bit,03/14/2018 10:57:00 AM,03/14/2018 10:57:00 AM,814 Stark Street in Austin (TX),Stray,Normal,Dog,Neutered Male,2 years,Rat Terrier Mix,Tricolor/Brown Brindle
48508,A721033,Lil Bit,04/26/2019 10:28:00 AM,04/26/2019 10:28:00 AM,South 1St And Stassney in Austin (TX),Public Assist,Normal,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
49093,A721033,Lil Bit,04/12/2018 10:14:00 AM,04/12/2018 10:14:00 AM,Austin (TX),Public Assist,Normal,Dog,Neutered Male,2 years,Rat Terrier Mix,Tricolor/Brown Brindle
55351,A721033,Lil Bit,02/16/2019 10:30:00 AM,02/16/2019 10:30:00 AM,1135 Airport Blvd in Austin (TX),Public Assist,Normal,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
60154,A721033,Lil Bit,12/17/2018 04:52:00 PM,12/17/2018 04:52:00 PM,1144 Airport in Austin (TX),Public Assist,Normal,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
67661,A721033,Lil Bit,04/22/2018 02:40:00 PM,04/22/2018 02:40:00 PM,South First Street And Oltorf Street in Austin...,Stray,Normal,Dog,Neutered Male,2 years,Rat Terrier Mix,Tricolor/Brown Brindle
78750,A721033,Lil Bit,11/19/2018 07:53:00 PM,11/19/2018 07:53:00 PM,9300 S Ih 35 in Austin (TX),Public Assist,Normal,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
87502,A721033,Lil Bit,02/06/2017 10:13:00 AM,02/06/2017 10:13:00 AM,6210 E Ben White in Austin (TX),Public Assist,Normal,Dog,Neutered Male,1 year,Rat Terrier Mix,Tricolor/Brown Brindle
88173,A721033,Lil Bit,02/20/2016 10:44:00 AM,02/20/2016 10:44:00 AM,2508 E Riverside Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,9 months,Rat Terrier Mix,Tricolor/Brown Brindle
92086,A721033,Lil Bit,09/16/2019 02:06:00 PM,09/16/2019 02:06:00 PM,Justin Lane And North Lamar in Austin (TX),Public Assist,Normal,Dog,Neutered Male,4 years,Rat Terrier Mix,Tricolor/Brown Brindle
93899,A721033,Lil Bit,05/22/2018 01:48:00 PM,05/22/2018 01:48:00 PM,W Oltorf And S 1St St in Austin (TX),Public Assist,Normal,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
100965,A721033,Lil Bit,01/09/2017 02:26:00 PM,01/09/2017 02:26:00 PM,6210 E Ben White Blvd in Austin (TX),Stray,Injured,Dog,Neutered Male,1 year,Rat Terrier Mix,Tricolor/Brown Brindle
103820,A721033,Lil Bit,09/03/2016 02:30:00 PM,09/03/2016 02:30:00 PM,6010 E Riverside in Austin (TX),Public Assist,Normal,Dog,Neutered Male,1 year,Rat Terrier Mix,Tricolor/Brown Brindle
107227,A721033,Lil Bit,01/26/2017 06:55:00 AM,01/26/2017 06:55:00 AM,901 W Ben White Blvd in Austin (TX),Public Assist,Normal,Dog,Neutered Male,1 year,Rat Terrier Mix,Tricolor/Brown Brindle
109617,A721033,Lil Bit,08/06/2018 07:00:00 PM,08/06/2018 07:00:00 PM,606 West Slaughter in Austin (TX),Public Assist,Normal,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
114936,A721033,Lil Bit,08/18/2018 09:45:00 PM,08/18/2018 09:45:00 PM,1500 Red River Street in Austin (TX),Public Assist,Normal,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
117612,A721033,Lil Bit,02/22/2018 10:28:00 AM,02/22/2018 10:28:00 AM,6400 Ben White Blvd in Austin (TX),Public Assist,Normal,Dog,Neutered Male,2 years,Rat Terrier Mix,Tricolor/Brown Brindle

In [20]:
outcomes[outcomes['Animal ID']=='A721033']

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color
4192,A721033,Lil Bit,08/10/2019 11:56:00 AM,08/10/2019 11:56:00 AM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,4 years,Rat Terrier Mix,Tricolor/Brown Brindle
9312,A721033,Lil Bit,01/10/2017 04:20:00 PM,01/10/2017 04:20:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,1 year,Rat Terrier Mix,Tricolor/Brown Brindle
11767,A721033,Lil Bit,10/21/2016 06:55:00 PM,10/21/2016 06:55:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,1 year,Rat Terrier Mix,Tricolor/Brown Brindle
14205,A721033,Lil Bit,03/11/2019 04:27:00 PM,03/11/2019 04:27:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
16728,A721033,Lil Bit,05/21/2019 02:42:00 PM,05/21/2019 02:42:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,4 years,Rat Terrier Mix,Tricolor/Brown Brindle
20707,A721033,Lil Bit,11/24/2018 04:25:00 PM,11/24/2018 04:25:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
23250,A721033,Lil Bit,03/16/2018 04:04:00 PM,03/16/2018 04:04:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,2 years,Rat Terrier Mix,Tricolor/Brown Brindle
26506,A721033,Lil Bit,05/04/2019 08:37:00 AM,05/04/2019 08:37:00 AM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
31469,A721033,Lil Bit,02/18/2019 04:46:00 PM,02/18/2019 04:46:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
35689,A721033,Lil Bit,01/28/2017 03:22:00 PM,01/28/2017 03:22:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,1 year,Rat Terrier Mix,Tricolor/Brown Brindle
36407,A721033,Lil Bit,08/22/2018 01:21:00 PM,08/22/2018 01:21:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
43624,A721033,Lil Bit,04/24/2018 04:12:00 PM,04/24/2018 04:12:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,2 years,Rat Terrier Mix,Tricolor/Brown Brindle
43853,A721033,Lil Bit,02/26/2019 07:00:00 PM,02/26/2019 07:00:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
46629,A721033,Lil Bit,09/25/2018 06:14:00 PM,09/25/2018 06:14:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
50394,A721033,Lil Bit,04/11/2018 12:37:00 PM,04/11/2018 12:37:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,2 years,Rat Terrier Mix,Tricolor/Brown Brindle
57645,A721033,Lil Bit,02/07/2017 05:26:00 PM,02/07/2017 05:26:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,1 year,Rat Terrier Mix,Tricolor/Brown Brindle
57883,A721033,Lil Bit,09/19/2019 11:02:00 AM,09/19/2019 11:02:00 AM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,4 years,Rat Terrier Mix,Tricolor/Brown Brindle
58950,A721033,Lil Bit,08/09/2018 11:13:00 AM,08/09/2018 11:13:00 AM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
59006,A721033,Lil Bit,07/11/2016 05:44:00 PM,07/11/2016 05:44:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,1 year,Rat Terrier Mix,Tricolor/Brown Brindle
62297,A721033,Lil Bit,10/20/2019 11:35:00 AM,10/20/2019 11:35:00 AM,05/20/2015,Rto-Adopt,NaN,Dog,Neutered Male,4 years,Rat Terrier Mix,Tricolor/Brown Brindle
63277,A721033,Lil Bit,02/20/2016 04:18:00 PM,02/20/2016 04:18:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,9 months,Rat Terrier Mix,Tricolor/Brown Brindle
70775,A721033,Lil Bit,02/02/2017 11:19:00 AM,02/02/2017 11:19:00 AM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,1 year,Rat Terrier Mix,Tricolor/Brown Brindle
71017,A721033,Lil Bit,09/23/2018 02:22:00 PM,09/23/2018 02:22:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
75345,A721033,Lil Bit,09/08/2018 01:55:00 PM,09/08/2018 01:55:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
77136,A721033,Lil Bit,02/23/2018 01:06:00 PM,02/23/2018 01:06:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,2 years,Rat Terrier Mix,Tricolor/Brown Brindle
80432,A721033,Lil Bit,12/27/2018 03:41:00 PM,12/27/2018 03:41:00 PM,05/20/2015,Rto-Adopt,NaN,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
81191,A721033,Lil Bit,03/16/2017 12:50:00 PM,03/16/2017 12:50:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,1 year,Rat Terrier Mix,Tricolor/Brown Brindle
83646,A721033,Lil Bit,12/16/2016 11:32:00 AM,12/16/2016 11:32:00 AM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,1 year,Rat Terrier Mix,Tricolor/Brown Brindle
84802,A721033,Lil Bit,09/12/2016 01:40:00 PM,09/12/2016 01:40:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,1 year,Rat Terrier Mix,Tricolor/Brown Brindle
92677,A721033,Lil Bit,03/08/2018 03:04:00 PM,03/08/2018 03:04:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,2 years,Rat Terrier Mix,Tricolor/Brown Brindle
110834,A721033,Lil Bit,04/17/2018 11:07:00 AM,04/17/2018 11:07:00 AM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,2 years,Rat Terrier Mix,Tricolor/Brown Brindle
115867,A721033,Lil Bit,02/12/2019 03:20:00 PM,02/12/2019 03:20:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle
119067,A721033,Lil Bit,05/26/2018 03:52:00 PM,05/26/2018 03:52:00 PM,05/20/2015,Return to Owner,NaN,Dog,Neutered Male,3 years,Rat Terrier Mix,Tricolor/Brown Brindle

In [ ]:
#we would need to come up with a method for multiple intake/outcomes with same dog or exclude

In [ ]:
#merge tests - drop dupes at first just ot see others

In [30]:
intakes_no_dupes = intakes.drop_duplicates(subset=['Animal ID'], keep='last')

In [31]:
intakes_no_dupes.shape

(115865, 12)

In [32]:
outcomes_no_dupes = outcomes.drop_duplicates(subset=['Animal ID'], keep='last')

In [33]:
outcomes_no_dupes.shape

(115849, 12)

In [34]:
df_merge = pd.merge(intakes_no_dupes, outcomes_no_dupes, how='inner', on ='Animal ID' )

In [38]:
df_merge.head()

,Animal ID,Name_x,DateTime_x,MonthYear_x,Found Location,Intake Type,Intake Condition,Animal Type_x,Sex upon Intake,Age upon Intake,Breed_x,Color_x,Name_y,DateTime_y,MonthYear_y,Date of Birth,Outcome Type,Outcome Subtype,Animal Type_y,Sex upon Outcome,Age upon Outcome,Breed_y,Color_y
0,A786884,*Brock,01/03/2019 04:19:00 PM,01/03/2019 04:19:00 PM,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,2 years,Beagle Mix,Tricolor,*Brock,01/08/2019 03:11:00 PM,01/08/2019 03:11:00 PM,01/03/2017,Transfer,Partner,Dog,Neutered Male,2 years,Beagle Mix,Tricolor
1,A706918,Belle,07/05/2015 12:59:00 PM,07/05/2015 12:59:00 PM,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver,Belle,07/05/2015 03:13:00 PM,07/05/2015 03:13:00 PM,07/05/2007,Return to Owner,NaN,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver
2,A724273,Runster,04/14/2016 06:43:00 PM,04/14/2016 06:43:00 PM,2818 Palomino Trail in Austin (TX),Stray,Normal,Dog,Intact Male,11 months,Basenji Mix,Sable/White,Runster,04/21/2016 05:17:00 PM,04/21/2016 05:17:00 PM,04/17/2015,Return to Owner,NaN,Dog,Neutered Male,1 year,Basenji Mix,Sable/White
3,A665644,NaN,10/21/2013 07:59:00 AM,10/21/2013 07:59:00 AM,Austin (TX),Stray,Sick,Cat,Intact Female,4 weeks,Domestic Shorthair Mix,Calico,NaN,10/21/2013 11:39:00 AM,10/21/2013 11:39:00 AM,09/21/2013,Transfer,Partner,Cat,Intact Female,4 weeks,Domestic Shorthair Mix,Calico
4,A682524,Rio,06/29/2014 10:38:00 AM,06/29/2014 10:38:00 AM,800 Grove Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,Rio,07/02/2014 02:16:00 PM,07/02/2014 02:16:00 PM,06/29/2010,Return to Owner,NaN,Dog,Neutered Male,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray

In [36]:
df_merge.shape

(115035, 23)